apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-microservice-deployment
  labels:
    app: aline-financial-banking  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-financial-banking  
  template:
    metadata:
      labels:
        app: aline-financial-banking  
    spec:
      containers:  
      - name: bank-microservice
        image: ${AWS_ID}.dkr.ecr.${AWS_ECR_REGION}.amazonaws.com/bank-microservice
        ports:
          - name: bank
            containerPort: 8083
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: aline-configmap
              key: BANK_PORT
        envFrom:
        - secretRef:
            name: mysqldb-secret