apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-microservice-deployment
  labels:
    app: aline-financial-banking  
    role: backend
spec:
  selector:
    matchLabels:
      app: aline-financial-banking  
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aline-financial-banking  
        role: backend
    spec:
      containers:  
      - name: bank-microservice
        image: ${AWS_ID}.dkr.ecr.${AWS_ECR_REGION}.amazonaws.com/bank-microservice
        ports:
          - name: bank
            containerPort: 8083
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: aline-configmap
              key: BANK_PORT
        envFrom:
        - secretRef:
            name: mysqldb-secret
        resources:
          requests:
            memory: ${BANK_MEMORY_REQUEST}
            cpu: ${BANK_CPU_REQUEST}
          limits:
            memory: ${BANK_MEMORY_LIMIT}
            cpu: ${BANK_CPU_LIMIT}
