apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: aline-financial-banking  
    role: gateway
spec:
  selector:
    matchLabels:
      app: aline-financial-banking  
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aline-financial-banking  
        role: gateway
    spec:
      containers:  
      - name: gateway
        image: ${AWS_ID}.dkr.ecr.${AWS_ECR_REGION}.amazonaws.com/gateway
        ports:
          - containerPort: 8080
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: aline-configmap
              key: GATEWAY_PORT
        - name: APP_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: aline-configmap
              key: APP_SERVICE_HOST
        envFrom:
        - secretRef:
            name: mysqldb-secret
        resources:
          requests:
            memory: ${GATEWAY_MEMORY_REQUEST}
            cpu: ${GATEWAY_CPU_REQUEST}
          limits:
            memory: ${GATEWAY_MEMORY_LIMIT}
            cpu: ${GATEWAY_CPU_LIMIT}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    role: gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
