apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: aline-financial-banking  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-financial-banking  
  template:
    metadata:
      labels:
        app: aline-financial-banking  
    spec:
      containers:  
      - name: gateway
        image: ${AWS_ID}.dkr.ecr.${AWS_ECR_REGION}.amazonaws.com/gateway
        ports:
          - containerPort: 8080
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: aline-configmap
              key: GATEWAY_PORT
        - name: APP_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: aline-configmap
              key: APP_SERVICE_HOST
        envFrom:
        - secretRef:
            name: mysqldb-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: aline-financial-banking
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
