apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-microservice-deployment
  labels:
    app: aline-financial-banking
spec:
  selector:
    matchLabels:
      app: aline-financial-banking 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aline-financial-banking
    spec:
      containers: 
      - name: transaction-microservice
        image: ${AWS_ID}.dkr.ecr.${AWS_ECR_REGION}.amazonaws.com/transaction-microservice
        ports:
          - name: transaction
            containerPort: 8073
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: aline-configmap
              key: TRANSACTION_PORT
        envFrom:
        - secretRef:
            name: mysqldb-secret
        resources:
          requests:
            memory: ${TRANSACTION_MEMORY_REQUEST}
            cpu: ${TRANSACTION_CPU_REQUEST}
          limits:
            memory: ${TRANSACTION_MEMORY_LIMIT}
            cpu: ${TRANSACTION_CPU_LIMIT}
