apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-microservice-deployment
  labels:
    app: aline-financial-banking 
spec:
  selector:
    matchLabels:
      app: aline-financial-banking 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aline-financial-banking 
    spec:
      containers: 
      - name: underwriter-microservice
        image: ${AWS_ID}.dkr.ecr.${AWS_ECR_REGION}.amazonaws.com/underwriter-microservice
        ports:
          - name: underwriter
            containerPort: 8071
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: aline-configmap
              key: UNDERWRITER_PORT
        envFrom:
        - secretRef:
            name: mysqldb-secret
        resources:
          requests:
            memory: ${UNDERWRITER_MEMORY_REQUEST}
            cpu: ${UNDERWRITER_CPU_REQUEST}
          limits:
            memory: ${UNDERWRITER_MEMORY_LIMIT}
            cpu: ${UNDERWRITER_CPU_LIMIT}
