apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deployment
  labels:
    app: aline-financial-banking 
    role: backend
spec:
  selector:
    matchLabels:
      app: aline-financial-banking 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aline-financial-banking 
        role: backend
    spec:
      containers:
      - name: user-microservice
        image: ${AWS_ID}.dkr.ecr.${AWS_ECR_REGION}.amazonaws.com/user-microservice
        ports:
          - name: user
            containerPort: 8070
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: aline-configmap
              key: USER_PORT
        envFrom:
        - secretRef:
            name: mysqldb-secret
        resources:
          requests:
            memory: ${USER_MEMORY_REQUEST}
            cpu: ${USER_CPU_REQUEST}
          limits:
            memory: ${USER_MEMORY_LIMIT}
            cpu: ${USER_CPU_LIMIT}
