---
- name: Install Docker on defined hosts
  hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ pem_key }}"
  
  tasks:
  - name: Install Docker Dependencies (Ubuntu)
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    when: ansible_distribution == "Ubuntu"

  - name: Install yum-utils package (CentOS)
    yum:
      name: yum-utils
      state: present
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Add Docker's official GPG key (Ubuntu)
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    when: ansible_distribution == "Ubuntu"

  - name: Set up stable Docker repository (Ubuntu)
    shell: |
      echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    when: ansible_distribution == "Ubuntu"

  - name: Set up the Docker repository (CentOS)
    become: yes
    shell: |
      yum-config-manager \
      --add-repo \
      https://download.docker.com/linux/centos/docker-ce.repo
    when: ansible_distribution == "CentOS"

  - name: Install Docker Engine (Ubuntu)
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    when: ansible_distribution == "Ubuntu"

  - name: Install Docker Engine (CentOS)
    yum:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    when: ansible_distribution == "CentOS"

  - name: Start Docker service (CentOS)
    shell: systemctl start docker
    when: ansible_distribution == "CentOS"
