version: '3'
services:
  bank-microservice:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/bank-microservice
    env_file: 
      - ./envs/bank.env
      - ./envs/common.env
    ports:
      - "8083:8083"
    depends_on:
      - database
    restart: on-failure:2
  transaction-microservice:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/transaction-microservice
    env_file: 
      - ./envs/transaction.env
      - ./envs/common.env
    ports:
      - "8073:8073"
    depends_on:
      - database
    restart: on-failure:2
  underwriter-microservice:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/underwriter-microservice
    env_file: 
      - ./envs/underwriter.env
      - ./envs/common.env
    ports:
      - "8071:8071"
    depends_on:
      - database
    restart: on-failure:2
  user-microservice:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/user-microservice
    env_file: 
      - ./envs/user.env
      - ./envs/common.env
    ports:
      - "8070:8070"
    depends_on:
      - database
    restart: on-failure:2
  gateway:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gateway
    env_file:
      - ./envs/gateway.env
    ports:
      - "8080:8080"
    depends_on:
      - bank-microservice
      - transaction-microservice
      - underwriter-microservice
      - user-microservice
