apiVersion: v1
kind: Service
metadata:
  name: backend-services
spec:
  type: ClusterIP
  selector:
    app: aline-financial-banking
  ports:
    - name: bank
      protocol: TCP
      port: 8083
      targetPort: bank
    - name: transaction
      protocol: TCP
      port: 8073
      targetPort: transaction
    - name: underwriter
      protocol: TCP
      port: 8071
      targetPort: underwriter
    - name: user
      protocol: TCP
      port: 8070
      targetPort: user
    